Set up documentation
CliMA/Solvent.jl pull request #19
Opened 2020-11-04 18:46 UTC by jb-mackay

Sets up Documenter.jl infrastructure and adds documentation for linear solvers and preconditioners.

Removes extra PCInitialize calls in specific solver implementations.

2020-11-04 19:23 UTC, simonbyrne commented on .gitignore
> +*.DS_Store
this is an OS-specific file. It should probably go in your global `core.excludesFile`, which by default is `~/.config/git/ignore`. See https://git-scm.com/docs/gitignore

2020-11-04 19:25 UTC, simonbyrne commented on .gitignore
> +*.DS_Store
and then you can delete the `git rm docs/.DS_Store`

2020-11-04 19:25 UTC, simonbyrne commented on docs/make.jl
> +# )
uncomment this.

2020-11-09 06:32 UTC, thomasgibson requested changes
Please remove `docs/.DS_Store` then this should be good to go!

2020-11-09 16:43 UTC, simonbyrne approved these changes

2020-11-09 16:44 UTC, merged